// Code generated by go-swagger; DO NOT EDIT.

// Package restapi BlogPost
//
//	REST API implementation for a simple blog post system
//	Schemes:
//	  http
//	Host: localhost:3000
//	BasePath: /
//	Version: 1.0
//	Contact: John Antony<john.k.antony@gmail.com>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
