// Code generated by go-swagger; DO NOT EDIT.

package blog_post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/john-k-antony/richpanel-blogposts-golang/models/apimodels"
)

// CreateBlogpostCreatedCode is the HTTP code returned for type CreateBlogpostCreated
const CreateBlogpostCreatedCode int = 201

/*
CreateBlogpostCreated Blog post created

swagger:response createBlogpostCreated
*/
type CreateBlogpostCreated struct {

	/*
	  In: Body
	*/
	Payload *apimodels.Blogpost `json:"body,omitempty"`
}

// NewCreateBlogpostCreated creates CreateBlogpostCreated with default headers values
func NewCreateBlogpostCreated() *CreateBlogpostCreated {

	return &CreateBlogpostCreated{}
}

// WithPayload adds the payload to the create blogpost created response
func (o *CreateBlogpostCreated) WithPayload(payload *apimodels.Blogpost) *CreateBlogpostCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create blogpost created response
func (o *CreateBlogpostCreated) SetPayload(payload *apimodels.Blogpost) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBlogpostCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBlogpostBadRequestCode is the HTTP code returned for type CreateBlogpostBadRequest
const CreateBlogpostBadRequestCode int = 400

/*
CreateBlogpostBadRequest Bad request

swagger:response createBlogpostBadRequest
*/
type CreateBlogpostBadRequest struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ResponseError `json:"body,omitempty"`
}

// NewCreateBlogpostBadRequest creates CreateBlogpostBadRequest with default headers values
func NewCreateBlogpostBadRequest() *CreateBlogpostBadRequest {

	return &CreateBlogpostBadRequest{}
}

// WithPayload adds the payload to the create blogpost bad request response
func (o *CreateBlogpostBadRequest) WithPayload(payload *apimodels.ResponseError) *CreateBlogpostBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create blogpost bad request response
func (o *CreateBlogpostBadRequest) SetPayload(payload *apimodels.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBlogpostBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBlogpostUnauthorizedCode is the HTTP code returned for type CreateBlogpostUnauthorized
const CreateBlogpostUnauthorizedCode int = 401

/*
CreateBlogpostUnauthorized Unauthenticated Request

swagger:response createBlogpostUnauthorized
*/
type CreateBlogpostUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ResponseError `json:"body,omitempty"`
}

// NewCreateBlogpostUnauthorized creates CreateBlogpostUnauthorized with default headers values
func NewCreateBlogpostUnauthorized() *CreateBlogpostUnauthorized {

	return &CreateBlogpostUnauthorized{}
}

// WithPayload adds the payload to the create blogpost unauthorized response
func (o *CreateBlogpostUnauthorized) WithPayload(payload *apimodels.ResponseError) *CreateBlogpostUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create blogpost unauthorized response
func (o *CreateBlogpostUnauthorized) SetPayload(payload *apimodels.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBlogpostUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBlogpostUnprocessableEntityCode is the HTTP code returned for type CreateBlogpostUnprocessableEntity
const CreateBlogpostUnprocessableEntityCode int = 422

/*
CreateBlogpostUnprocessableEntity Invalid request

swagger:response createBlogpostUnprocessableEntity
*/
type CreateBlogpostUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ResponseError `json:"body,omitempty"`
}

// NewCreateBlogpostUnprocessableEntity creates CreateBlogpostUnprocessableEntity with default headers values
func NewCreateBlogpostUnprocessableEntity() *CreateBlogpostUnprocessableEntity {

	return &CreateBlogpostUnprocessableEntity{}
}

// WithPayload adds the payload to the create blogpost unprocessable entity response
func (o *CreateBlogpostUnprocessableEntity) WithPayload(payload *apimodels.ResponseError) *CreateBlogpostUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create blogpost unprocessable entity response
func (o *CreateBlogpostUnprocessableEntity) SetPayload(payload *apimodels.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBlogpostUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
