// Code generated by go-swagger; DO NOT EDIT.

package blog_post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/john-k-antony/richpanel-blogposts-golang/models"
)

// DeleteBlogpostByIDHandlerFunc turns a function with the right signature into a delete blogpost by Id handler
type DeleteBlogpostByIDHandlerFunc func(DeleteBlogpostByIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteBlogpostByIDHandlerFunc) Handle(params DeleteBlogpostByIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteBlogpostByIDHandler interface for that can handle valid delete blogpost by Id params
type DeleteBlogpostByIDHandler interface {
	Handle(DeleteBlogpostByIDParams, *models.Principal) middleware.Responder
}

// NewDeleteBlogpostByID creates a new http.Handler for the delete blogpost by Id operation
func NewDeleteBlogpostByID(ctx *middleware.Context, handler DeleteBlogpostByIDHandler) *DeleteBlogpostByID {
	return &DeleteBlogpostByID{Context: ctx, Handler: handler}
}

/*
	DeleteBlogpostByID swagger:route DELETE /posts/{id} BlogPost deleteBlogpostById

# Delete blog post information

Delete an existing blog post with the matching id.
*/
type DeleteBlogpostByID struct {
	Context *middleware.Context
	Handler DeleteBlogpostByIDHandler
}

func (o *DeleteBlogpostByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteBlogpostByIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
