// Code generated by go-swagger; DO NOT EDIT.

package blog_post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/john-k-antony/richpanel-blogposts-golang/models/apimodels"
)

// GetBlogpostByIDOKCode is the HTTP code returned for type GetBlogpostByIDOK
const GetBlogpostByIDOKCode int = 200

/*
GetBlogpostByIDOK Blog post found

swagger:response getBlogpostByIdOK
*/
type GetBlogpostByIDOK struct {

	/*
	  In: Body
	*/
	Payload *apimodels.Blogpost `json:"body,omitempty"`
}

// NewGetBlogpostByIDOK creates GetBlogpostByIDOK with default headers values
func NewGetBlogpostByIDOK() *GetBlogpostByIDOK {

	return &GetBlogpostByIDOK{}
}

// WithPayload adds the payload to the get blogpost by Id o k response
func (o *GetBlogpostByIDOK) WithPayload(payload *apimodels.Blogpost) *GetBlogpostByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get blogpost by Id o k response
func (o *GetBlogpostByIDOK) SetPayload(payload *apimodels.Blogpost) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlogpostByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBlogpostByIDUnauthorizedCode is the HTTP code returned for type GetBlogpostByIDUnauthorized
const GetBlogpostByIDUnauthorizedCode int = 401

/*
GetBlogpostByIDUnauthorized Unauthenticated Request

swagger:response getBlogpostByIdUnauthorized
*/
type GetBlogpostByIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ResponseError `json:"body,omitempty"`
}

// NewGetBlogpostByIDUnauthorized creates GetBlogpostByIDUnauthorized with default headers values
func NewGetBlogpostByIDUnauthorized() *GetBlogpostByIDUnauthorized {

	return &GetBlogpostByIDUnauthorized{}
}

// WithPayload adds the payload to the get blogpost by Id unauthorized response
func (o *GetBlogpostByIDUnauthorized) WithPayload(payload *apimodels.ResponseError) *GetBlogpostByIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get blogpost by Id unauthorized response
func (o *GetBlogpostByIDUnauthorized) SetPayload(payload *apimodels.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlogpostByIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBlogpostByIDNotFoundCode is the HTTP code returned for type GetBlogpostByIDNotFound
const GetBlogpostByIDNotFoundCode int = 404

/*
GetBlogpostByIDNotFound Blog post not found

swagger:response getBlogpostByIdNotFound
*/
type GetBlogpostByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ResponseError `json:"body,omitempty"`
}

// NewGetBlogpostByIDNotFound creates GetBlogpostByIDNotFound with default headers values
func NewGetBlogpostByIDNotFound() *GetBlogpostByIDNotFound {

	return &GetBlogpostByIDNotFound{}
}

// WithPayload adds the payload to the get blogpost by Id not found response
func (o *GetBlogpostByIDNotFound) WithPayload(payload *apimodels.ResponseError) *GetBlogpostByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get blogpost by Id not found response
func (o *GetBlogpostByIDNotFound) SetPayload(payload *apimodels.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlogpostByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
